
package sde.project.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RecomService", targetNamespace = "http://soap.project.sde/", wsdlLocation = "http://beer-recom.herokuapp.com:80/ws/beer?wsdl")
public class RecomService
    extends Service
{

    private final static URL RECOMSERVICE_WSDL_LOCATION;
    private final static WebServiceException RECOMSERVICE_EXCEPTION;
    private final static QName RECOMSERVICE_QNAME = new QName("http://soap.project.sde/", "RecomService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://beer-recom.herokuapp.com:80/ws/beer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECOMSERVICE_WSDL_LOCATION = url;
        RECOMSERVICE_EXCEPTION = e;
    }

    public RecomService() {
        super(__getWsdlLocation(), RECOMSERVICE_QNAME);
    }

    public RecomService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECOMSERVICE_QNAME, features);
    }

    public RecomService(URL wsdlLocation) {
        super(wsdlLocation, RECOMSERVICE_QNAME);
    }

    public RecomService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECOMSERVICE_QNAME, features);
    }

    public RecomService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecomService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BeerInterf
     */
    @WebEndpoint(name = "BeerImplPort")
    public BeerInterf getBeerImplPort() {
        return super.getPort(new QName("http://soap.project.sde/", "BeerImplPort"), BeerInterf.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BeerInterf
     */
    @WebEndpoint(name = "BeerImplPort")
    public BeerInterf getBeerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.project.sde/", "BeerImplPort"), BeerInterf.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECOMSERVICE_EXCEPTION!= null) {
            throw RECOMSERVICE_EXCEPTION;
        }
        return RECOMSERVICE_WSDL_LOCATION;
    }

}
