
package sde.project.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BeerInterf", targetNamespace = "http://soap.project.sde/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BeerInterf {


    /**
     * 
     * @return
     *     returns java.util.List<sde.project.soap.Beer>
     */
    @WebMethod
    @WebResult(name = "beer", targetNamespace = "")
    @RequestWrapper(localName = "readBeerList", targetNamespace = "http://soap.project.sde/", className = "sde.project.soap.ReadBeerList")
    @ResponseWrapper(localName = "readBeerListResponse", targetNamespace = "http://soap.project.sde/", className = "sde.project.soap.ReadBeerListResponse")
    @Action(input = "http://soap.project.sde/BeerInterf/readBeerListRequest", output = "http://soap.project.sde/BeerInterf/readBeerListResponse")
    public List<Beer> readBeerList();

    /**
     * 
     * @param beer
     */
    @WebMethod
    @RequestWrapper(localName = "createBeer", targetNamespace = "http://soap.project.sde/", className = "sde.project.soap.CreateBeer")
    @ResponseWrapper(localName = "createBeerResponse", targetNamespace = "http://soap.project.sde/", className = "sde.project.soap.CreateBeerResponse")
    @Action(input = "http://soap.project.sde/BeerInterf/createBeerRequest", output = "http://soap.project.sde/BeerInterf/createBeerResponse")
    public void createBeer(
        @WebParam(name = "beer", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<Beer> beer);

    /**
     * 
     * @param beer
     */
    @WebMethod
    @RequestWrapper(localName = "updateBeer", targetNamespace = "http://soap.project.sde/", className = "sde.project.soap.UpdateBeer")
    @ResponseWrapper(localName = "updateBeerResponse", targetNamespace = "http://soap.project.sde/", className = "sde.project.soap.UpdateBeerResponse")
    @Action(input = "http://soap.project.sde/BeerInterf/updateBeerRequest", output = "http://soap.project.sde/BeerInterf/updateBeerResponse")
    public void updateBeer(
        @WebParam(name = "beer", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<Beer> beer);

    /**
     * 
     * @param idBeer
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(name = "beer", targetNamespace = "")
    @RequestWrapper(localName = "deleteBeer", targetNamespace = "http://soap.project.sde/", className = "sde.project.soap.DeleteBeer")
    @ResponseWrapper(localName = "deleteBeerResponse", targetNamespace = "http://soap.project.sde/", className = "sde.project.soap.DeleteBeerResponse")
    @Action(input = "http://soap.project.sde/BeerInterf/deleteBeerRequest", output = "http://soap.project.sde/BeerInterf/deleteBeerResponse")
    public long deleteBeer(
        @WebParam(name = "idBeer", targetNamespace = "")
        long idBeer);

    /**
     * 
     * @param user
     * @param beer
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(name = "beer", targetNamespace = "")
    @RequestWrapper(localName = "addBeerToUser", targetNamespace = "http://soap.project.sde/", className = "sde.project.soap.AddBeerToUser")
    @ResponseWrapper(localName = "addBeerToUserResponse", targetNamespace = "http://soap.project.sde/", className = "sde.project.soap.AddBeerToUserResponse")
    @Action(input = "http://soap.project.sde/BeerInterf/addBeerToUserRequest", output = "http://soap.project.sde/BeerInterf/addBeerToUserResponse")
    public long addBeerToUser(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "beer", targetNamespace = "")
        Beer beer);

    /**
     * 
     * @param user
     * @param value
     * @param beer
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "beer", targetNamespace = "")
    @RequestWrapper(localName = "rateUserBeer", targetNamespace = "http://soap.project.sde/", className = "sde.project.soap.RateUserBeer")
    @ResponseWrapper(localName = "rateUserBeerResponse", targetNamespace = "http://soap.project.sde/", className = "sde.project.soap.RateUserBeerResponse")
    @Action(input = "http://soap.project.sde/BeerInterf/rateUserBeerRequest", output = "http://soap.project.sde/BeerInterf/rateUserBeerResponse")
    public boolean rateUserBeer(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "beer", targetNamespace = "")
        Beer beer,
        @WebParam(name = "value", targetNamespace = "")
        int value);

    /**
     * 
     * @param user
     * @param beer
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(name = "beer", targetNamespace = "")
    @RequestWrapper(localName = "removeBeerToUser", targetNamespace = "http://soap.project.sde/", className = "sde.project.soap.RemoveBeerToUser")
    @ResponseWrapper(localName = "removeBeerToUserResponse", targetNamespace = "http://soap.project.sde/", className = "sde.project.soap.RemoveBeerToUserResponse")
    @Action(input = "http://soap.project.sde/BeerInterf/removeBeerToUserRequest", output = "http://soap.project.sde/BeerInterf/removeBeerToUserResponse")
    public long removeBeerToUser(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "beer", targetNamespace = "")
        Beer beer);

    /**
     * 
     * @param count
     * @param user
     * @return
     *     returns java.util.List<sde.project.soap.Beer>
     */
    @WebMethod
    @WebResult(name = "beer", targetNamespace = "")
    @RequestWrapper(localName = "getUserRecom", targetNamespace = "http://soap.project.sde/", className = "sde.project.soap.GetUserRecom")
    @ResponseWrapper(localName = "getUserRecomResponse", targetNamespace = "http://soap.project.sde/", className = "sde.project.soap.GetUserRecomResponse")
    @Action(input = "http://soap.project.sde/BeerInterf/getUserRecomRequest", output = "http://soap.project.sde/BeerInterf/getUserRecomResponse")
    public List<Beer> getUserRecom(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "count", targetNamespace = "")
        long count);

    /**
     * 
     * @param username
     * @return
     *     returns sde.project.soap.User
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "readUser", targetNamespace = "http://soap.project.sde/", className = "sde.project.soap.ReadUser")
    @ResponseWrapper(localName = "readUserResponse", targetNamespace = "http://soap.project.sde/", className = "sde.project.soap.ReadUserResponse")
    @Action(input = "http://soap.project.sde/BeerInterf/readUserRequest", output = "http://soap.project.sde/BeerInterf/readUserResponse")
    public User readUser(
        @WebParam(name = "username", targetNamespace = "")
        String username);

    /**
     * 
     * @return
     *     returns java.util.List<sde.project.soap.User>
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "readUserList", targetNamespace = "http://soap.project.sde/", className = "sde.project.soap.ReadUserList")
    @ResponseWrapper(localName = "readUserListResponse", targetNamespace = "http://soap.project.sde/", className = "sde.project.soap.ReadUserListResponse")
    @Action(input = "http://soap.project.sde/BeerInterf/readUserListRequest", output = "http://soap.project.sde/BeerInterf/readUserListResponse")
    public List<User> readUserList();

    /**
     * 
     * @param idBeer
     * @return
     *     returns sde.project.soap.Beer
     */
    @WebMethod
    @WebResult(name = "beer", targetNamespace = "")
    @RequestWrapper(localName = "readBeer", targetNamespace = "http://soap.project.sde/", className = "sde.project.soap.ReadBeer")
    @ResponseWrapper(localName = "readBeerResponse", targetNamespace = "http://soap.project.sde/", className = "sde.project.soap.ReadBeerResponse")
    @Action(input = "http://soap.project.sde/BeerInterf/readBeerRequest", output = "http://soap.project.sde/BeerInterf/readBeerResponse")
    public Beer readBeer(
        @WebParam(name = "idBeer", targetNamespace = "")
        long idBeer);

    /**
     * 
     * @param user
     * @return
     *     returns java.util.List<sde.project.soap.Beer>
     */
    @WebMethod
    @WebResult(name = "beer", targetNamespace = "")
    @RequestWrapper(localName = "readUserWL", targetNamespace = "http://soap.project.sde/", className = "sde.project.soap.ReadUserWL")
    @ResponseWrapper(localName = "readUserWLResponse", targetNamespace = "http://soap.project.sde/", className = "sde.project.soap.ReadUserWLResponse")
    @Action(input = "http://soap.project.sde/BeerInterf/readUserWLRequest", output = "http://soap.project.sde/BeerInterf/readUserWLResponse")
    public List<Beer> readUserWL(
        @WebParam(name = "user", targetNamespace = "")
        User user);

    /**
     * 
     * @param user
     * @param beer
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(name = "beer", targetNamespace = "")
    @RequestWrapper(localName = "addUserView", targetNamespace = "http://soap.project.sde/", className = "sde.project.soap.AddUserView")
    @ResponseWrapper(localName = "addUserViewResponse", targetNamespace = "http://soap.project.sde/", className = "sde.project.soap.AddUserViewResponse")
    @Action(input = "http://soap.project.sde/BeerInterf/addUserViewRequest", output = "http://soap.project.sde/BeerInterf/addUserViewResponse")
    public long addUserView(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "beer", targetNamespace = "")
        Beer beer);

    /**
     * 
     * @param user
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://soap.project.sde/", className = "sde.project.soap.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://soap.project.sde/", className = "sde.project.soap.DeleteUserResponse")
    @Action(input = "http://soap.project.sde/BeerInterf/deleteUserRequest", output = "http://soap.project.sde/BeerInterf/deleteUserResponse")
    public long deleteUser(
        @WebParam(name = "user", targetNamespace = "")
        User user);

    /**
     * 
     * @param user
     * @param beer
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "beer", targetNamespace = "")
    @RequestWrapper(localName = "getBeerRatingUser", targetNamespace = "http://soap.project.sde/", className = "sde.project.soap.GetBeerRatingUser")
    @ResponseWrapper(localName = "getBeerRatingUserResponse", targetNamespace = "http://soap.project.sde/", className = "sde.project.soap.GetBeerRatingUserResponse")
    @Action(input = "http://soap.project.sde/BeerInterf/getBeerRatingUserRequest", output = "http://soap.project.sde/BeerInterf/getBeerRatingUserResponse")
    public double getBeerRatingUser(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "beer", targetNamespace = "")
        Beer beer);

    /**
     * 
     * @param user
     */
    @WebMethod
    @RequestWrapper(localName = "createUser", targetNamespace = "http://soap.project.sde/", className = "sde.project.soap.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://soap.project.sde/", className = "sde.project.soap.CreateUserResponse")
    @Action(input = "http://soap.project.sde/BeerInterf/createUserRequest", output = "http://soap.project.sde/BeerInterf/createUserResponse")
    public void createUser(
        @WebParam(name = "user", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<User> user);

}
